name: kumino_cli
description: Command-line tools to improve development experience with Kumino.
version: 0.0.0
repository: https://github.com/dart-stack/kumino

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  build_test: ^2.2.2
  lints: ^3.0.0
  test: ^1.24.0
