name: bookstore_mvc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-282.2.beta

# Add regular dependencies here.
dependencies:
  kumino: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependency_overrides:
  kumino:
    path: ../..
